# Generated by Django 4.2.13 on 2024-07-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spa_home', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
